### ISSUE TITLE
nil value

### ISSUE THREAD

**Issue by tieumieu90** [VenomXNL/XNLRankBar#1]
![image](https://user-images.githubusercontent.com/44625876/86515727-22f91400-bde9-11ea-89a8-97f10864aff6.png)

**Comment by VenomXNL** [comment]
Help for such problems can be found at the FiveM forum, as which is suggested/recommended in the documentation.

However this has literally **nothing** to do with my script ;), as your own error already states clearly:
There is something wrong where you try to read from a nil (empty/non declared) global names **ESX**

I'm SUSPECTING that this happens at the moment you are trying to set the initial XP levels (because it 'triggers' at line 274 which is right above: 
`function XNL_SetInitialXPLevels(CurrentXP, ShowRankBar, ShowRankBarAnimating)` 
Which is at line 278.

However because this clearly isn't a problem in my script, i'm closing this issue right away.

I would yet again recommend to get further assistance at the FiveM forum. :)
