### ISSUE TITLE
help!!!

### ISSUE THREAD

**Issue by MohaIQ61** [VenomXNL/XNLRankBar#2]
how can i link the script with esx_jobs and esx_scoreboard
plz

**Comment by VenomXNL** [comment]
I have no idea because that totally depends on esx and the scripts/plugins you've mentions (you need to alter those or make a plugin to link it with those).

This however is not an **issue** on this release.

For such help/info or guidance i would recommend looking at the FiveM forums instead of posting **release issues** on repository's.

IF i'm correct (somewhere) in the posts/reply's on my release on the FiveM website someone has made an ESX version/plugin of this rankbar.
