### ISSUE TITLE
Is it possible to get xp by killing a player? I need help.

### ISSUE THREAD

**Issue by TheChrisHp** [VenomXNL/XNLRankBar#4]

**Comment by TheChrisHp** [comment]
I have tried everything but I don't know how to do so that when I kill a player it gives me xp

**Comment by VenomXNL** [comment]
Maybe read the comments and documentation first ;)

It clearly states that this INTERFACE does NOTHING except providing you with an UI interface for your OWN ranking, scripting and frame work ;)

So Yes if you make your own script which awards players with XP AND also store it yourself in your own database (if you want it to be saved) you can indeed give players xp by killing others, but that has nothing to do with this interface ;)

**Comment by VenomXNL** [comment]
For further assistance on projects and servers please use the forums of FiveM (which are intended for this kind of help :) to me it sound like you need something like a framework or so (like vRP, ESX etc) so start with.

**Comment by TheChrisHp** [comment]
I know, the only thing is that I have doubts is that I do not know how to do so that by killing a player I can get XP, it seems strange to me that nobody has thought of creating a script like this, since programming my server and the only thing that I was able to achieve is to get closer to what I am looking for, which in this case would be to grant me experience when killing a player but it does so infinitely until the player revives. I do not think it is something difficult to program, however it costs me a lot to do it, can you help me in any way to solve it? I would really appreciate it. If not, nothing happens I understand and thank you in advance.

**Comment by VenomXNL** [comment]
" it seems strange to me that nobody has thought of creating a script like this" Lots of people and servers actually have this (mine included, except on mine players get an XP penalty for killing other players and get XP for completing jobs, tasks and missions together (CO-OP). 

However doing so would require some "basic" elements on the server like:
- User management (saving, updating and re-loading users on joining the server)
- User identification (either with password or game license) to ensure the correct people get their own stats when signing in.
- a database or any other method to store the data (stats etc) on the server which can be reloaded up login etc.
- and then the scripts themselves which grand XP, money or anything else during gameplay.

I suppose you can understand that a system like this isn't "simple"  to just make for a random (empty or clean for example) server, because it needs to be completly intergrated into the server. :)

HOWEVER... i would recommend to read a bit into the basics of LUA scripting, it's honeslty not that hard of a progamming syntax/language to learn, plus it has LOTS of open source examples online (nearly every fiveM script is basically "open source", and it also has lots of documentation availible online (LUA that is i mean).

IF it would have been just a simple 5 minute (or 'one hour') script to write for you (fully functional and useful), then i would not have minded to make a simple example, however unfortunately this isn't the case due to lots of dependency's like the server, script style of the server, user stats etc.

I'm sorry, and truly hope you are able to get some information and assistance from the FiveM forums for example to make it like you want :)

Trust me: Having your own FiveM server becomes so much more awesome and "unlimited" once you are able to make your own scripts :) it's well worth it.
